language: node_js

cache: yarn

node_js: 10

install:
  - yarn install --frozen-lockfile

script:
  - yarn build
  - yarn test --ci

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - yarn publish --tag beta
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script:
      - yarn exec semantic-release
    on:
      branch: master
